....
----------------------------------------------------------------------
Ran 4 tests in 0.011s

OK
...F..F
======================================================================
FAIL: test_get_group (__main__.TestYourWebserver)
how secure are you?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "not-free-tests.py", line 59, in test_get_group
    self.assertTrue( False, "Should have thrown an HTTP Error! [%d]" % req.getcode())
AssertionError: Should have thrown an HTTP Error! [200]

======================================================================
FAIL: test_html (__main__.TestYourWebserver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "not-free-tests.py", line 75, in test_html
    self.assertTrue( req.info().gettype() == "text/html", ("Bad mimetype for html! %s" % req.info().gettype()))
AssertionError: Bad mimetype for html! text/plain

----------------------------------------------------------------------
Ran 7 tests in 0.014s

FAILED (failures=2)
